# Generated by Django 2.2.12 on 2022-01-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='copyrightClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('footer', 'footer')], max_length=25, unique=True)),
                ('msg', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='FooterHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth')], max_length=25, unique=True)),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Nav_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_menu', models.CharField(choices=[('menu1', 'menu1'), ('menu2', 'menu2'), ('menu3', 'menu3'), ('menu4', 'menu4'), ('menu5', 'menu5')], default='icon1', max_length=20, unique=True)),
                ('menuname', models.CharField(max_length=15)),
                ('menuurl', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nav_social_media_icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_icon', models.CharField(choices=[('icon1', 'icon1'), ('icon2', 'icon2')], default='icon1', max_length=20, unique=True)),
                ('icon', models.CharField(max_length=30)),
                ('iconlink', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Navlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(choices=[('logo', 'logo')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('link', models.CharField(max_length=200)),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogtheme.FooterHeading')),
            ],
        ),
    ]
