# Generated by Django 2.2.12 on 2022-01-05 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='heading',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog/main_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
