# Generated by Django 2.2.12 on 2022-01-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
