# Generated by Django 2.2.12 on 2022-01-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='similar_posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='_blogpost_similar_posts_+', to='blog.blogpost'),
        ),
    ]
