# Generated by Django 3.2.8 on 2021-12-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='origin_url',
            new_name='original_url',
        ),
    ]
