# Generated by Django 3.2.8 on 2021-12-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_alter_shorturl_short_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
