# Generated by Django 2.2.12 on 2022-01-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0007_alter_shorturl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
